import type { Metadata } from "next";
import "./globals.css";
import { RouteProvider } from "@/context/RouteContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body>
        <RouteProvider>{children}</RouteProvider>
      </body>
    </html>
  );
}
